services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bank
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bank-db
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: bank_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
